"""
ProjectGabriel - Onboarding Configurator
Launches a web-based setup wizard that writes config.yml.
Run after setup.bat installs dependencies.
"""

import http.server
import json
import os
import sys
import threading
import urllib.request
import webbrowser
from pathlib import Path

import yaml

PORT = 8769
CONFIG_EXAMPLE = Path("config.yml.example")
CONFIG_OUTPUT = Path("config.yml")
PROMPTS_DIR = Path("config/prompts")
PROMPTS_OUTPUT = PROMPTS_DIR / "prompts.yml"
APPENDS_EXAMPLE = PROMPTS_DIR / "appends.yml.example"
APPENDS_OUTPUT = PROMPTS_DIR / "appends.yml"
ONBOARDING_HTML = Path("onboarding/index.html")


def get_audio_devices():
    """Try to list audio devices via PyAudio."""
    devices = []
    try:
        import pyaudio
        p = pyaudio.PyAudio()
        for i in range(p.get_device_count()):
            info = p.get_device_info_by_index(i)
            devices.append({
                "index": i,
                "name": info.get("name", f"Device {i}"),
                "max_input": info.get("maxInputChannels", 0),
                "max_output": info.get("maxOutputChannels", 0),
            })
        p.terminate()
    except Exception:
        pass
    return devices


def load_defaults():
    """Load config.yml.example as the default config."""
    if CONFIG_EXAMPLE.exists():
        with open(CONFIG_EXAMPLE, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    return {}


def deep_merge(base, override):
    """Recursively merge override into base dict."""
    result = dict(base)
    for k, v in override.items():
        if k in result and isinstance(result[k], dict) and isinstance(v, dict):
            result[k] = deep_merge(result[k], v)
        else:
            result[k] = v
    return result


def save_config(user_values):
    """Merge user values with defaults and write config.yml."""
    defaults = load_defaults()
    merged = deep_merge(defaults, user_values)
    with open(CONFIG_OUTPUT, "w", encoding="utf-8") as f:
        f.write("# ProjectGabriel Configuration\n")
        f.write("# Generated by the onboarding configurator.\n")
        f.write("# See config.yml.example for full documentation of all options.\n\n")
        yaml.dump(merged, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def save_prompts(prompt_data):
    """Write prompts.yml from user prompt data."""
    if not prompt_data:
        return
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    entry = {
        prompt_data["name"]: {
            "name": prompt_data["charName"],
            "description": prompt_data["desc"],
            "prompt": prompt_data["prompt"],
        }
    }
    with open(PROMPTS_OUTPUT, "w", encoding="utf-8") as f:
        f.write("# ProjectGabriel - AI Prompt\n")
        f.write("# Generated by the onboarding configurator.\n")
        f.write("# See prompts.yml.example for documentation.\n\n")
        yaml.dump(entry, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def save_appends(appends_data):
    """Copy appends.yml.example to appends.yml, replacing appearance/details."""
    if not appends_data:
        return
    if not APPENDS_EXAMPLE.exists():
        return
    content = APPENDS_EXAMPLE.read_text(encoding="utf-8")
    if appends_data.get("appearance"):
        content = content.replace(
            "Describe your avatar's appearance here.",
            appends_data["appearance"],
        )
    if appends_data.get("details"):
        content = content.replace(
            "Add personal details, friends, backstory here.",
            appends_data["details"],
        )
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(APPENDS_OUTPUT, "w", encoding="utf-8") as f:
        f.write(content)


class ConfigHandler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # suppress request logs

    def _json_response(self, data, status=200):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _html_response(self, html):
        body = html.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/" or self.path == "/index.html":
            if ONBOARDING_HTML.exists():
                html = ONBOARDING_HTML.read_text(encoding="utf-8")
                self._html_response(html)
            else:
                self._json_response({"error": "onboarding/index.html not found"}, 404)

        elif self.path == "/api/defaults":
            defaults = load_defaults()
            self._json_response(defaults)

        elif self.path == "/api/audio-devices":
            devices = get_audio_devices()
            self._json_response(devices)

        elif self.path == "/api/check-config":
            self._json_response({"exists": CONFIG_OUTPUT.exists()})

        elif self.path == "/api/shutdown":
            self._json_response({"success": True})
            threading.Thread(target=lambda: (server.shutdown()), daemon=True).start()

        else:
            # Serve static files from onboarding/
            MIME_TYPES = {".css": "text/css", ".js": "application/javascript", ".html": "text/html"}
            safe_path = Path("onboarding") / Path(self.path.lstrip("/"))
            if safe_path.exists() and safe_path.is_file() and Path("onboarding").resolve() in safe_path.resolve().parents:
                ext = safe_path.suffix.lower()
                content_type = MIME_TYPES.get(ext, "application/octet-stream")
                body = safe_path.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", content_type)
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            else:
                self.send_error(404)

    def do_POST(self):
        if self.path == "/api/save":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            try:
                data = json.loads(body)
                config_values = data.get("config", data)
                prompt_data = data.get("prompt")
                appends_data = data.get("appends")

                save_config(config_values)

                saved_files = [str(CONFIG_OUTPUT.resolve())]
                if prompt_data:
                    save_prompts(prompt_data)
                    saved_files.append(str(PROMPTS_OUTPUT.resolve()))
                if appends_data:
                    save_appends(appends_data)
                    saved_files.append(str(APPENDS_OUTPUT.resolve()))

                self._json_response({
                    "success": True,
                    "config_path": str(CONFIG_OUTPUT.resolve()),
                    "saved_files": saved_files,
                })
            except Exception as e:
                self._json_response({"error": str(e)}, 500)

        elif self.path == "/api/generate-prompt":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            try:
                data = json.loads(body)
                api_key = data["api_key"]
                system_prompt = data["system"]
                user_msg = data["user"]

                payload = json.dumps({
                    "contents": [{"role": "user", "parts": [{"text": user_msg}]}],
                    "systemInstruction": {"parts": [{"text": system_prompt}]},
                    "generationConfig": {"temperature": 1.0, "maxOutputTokens": 2048, "thinkingConfig": {"thinkingLevel": "low"}},
                }).encode()

                url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key={api_key}"
                req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
                with urllib.request.urlopen(req, timeout=30) as resp:
                    result = json.loads(resp.read().decode())

                text = result["candidates"][0]["content"]["parts"][0]["text"]
                self._json_response({"text": text})
            except urllib.error.HTTPError as e:
                err_body = e.read().decode() if e.readable() else str(e)
                self._json_response({"error": f"API error {e.code}: {err_body}"}, 500)
            except Exception as e:
                self._json_response({"error": str(e)}, 500)

        elif self.path == "/api/shutdown":
            self._json_response({"success": True})
            threading.Thread(target=lambda: (server.shutdown()), daemon=True).start()

        else:
            self.send_error(404)


def main():
    global server

    if not CONFIG_EXAMPLE.exists():
        print("Error: config.yml.example not found. Run from project root.")
        sys.exit(1)

    if not ONBOARDING_HTML.exists():
        print("Error: onboarding/index.html not found.")
        sys.exit(1)

    server = http.server.HTTPServer(("127.0.0.1", PORT), ConfigHandler)
    url = f"http://127.0.0.1:{PORT}"

    print()
    print("  ====================================================")
    print("       Project Gabriel - Configuration Wizard")
    print("  ====================================================")
    print()
    print(f"  Opening configurator at {url}")
    print("  Press Ctrl+C to cancel.")
    print()

    webbrowser.open(url)

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass

    server.server_close()

    if CONFIG_OUTPUT.exists():
        print("  Config saved! You can now run Gabriel:")
        print("    python supervisor.py")
    else:
        print("  No config saved. Run this again or edit config.yml manually.")
    print()


if __name__ == "__main__":
    main()
